[package]
name        = "sink"
version     = "0.1.0"
edition     = "2021"
authors     = ["Stausssi"]
description = "Universal, extensible package manager."
license     = "MIT"
repository  = "https://github.com/Stausssi/sink"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap       = { version = "4.4.7", features = ["derive"] }
env_logger = "0.10.0"
log        = "0.4.20"
serde      = { version = "1.0.190", features = ["derive"] }
toml       = "0.8.6"
