# Optional: The default owner to fall back to if not explicitly set
default-owner = "Stausssi"

# With optional includes you can split the dependencies into multiple files
includes = [
    "path/to/other/sink.toml",
]

# The dependency table contains all assets to sync
[dependencies]

# This will sync version v1.2.3 of 'sink_example.toml' from the default owner and repository into the directory the sink.toml is in
"sink_example.toml" = "v1.2.3"

    # Dependencies can be specified in tables to allow for more complex configurations
    [dependencies."file-*.json"]
    # The origin consists of the owner and repository
    # If no owner is specified, the default owner is used
    origin = "Stausssi/Stausssi"
    # Version can be any git release tag, defaults to the latest available release if not set
    version = "latest"
    # The destination to download the file(s) to
    destination = "./imported/"
    # Whether the file should be put into the .gitignore
    gitignore = true
