name: Check code quality
run-name: Check code quality for ${{ github.ref }}

on: 
  push:
  workflow_dispatch: 

jobs:
  check-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Check formatting
        if: always()
        run: cargo fmt --check
      
      - name: Check package
        if: always()
        run: cargo check

      - name: Check linter (clippy)
        if: always()
        run: cargo clippy --all-targets --all-features
