name: 🦀 Check code quality
run-name: Check code quality for ${{ github.ref }}

on:
  push:
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-rust:
    name: Check Rust
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Check formatting
        if: always()
        run: cargo fmt --check

      - name: Check package
        if: always()
        run: cargo check

      - name: Check linter (clippy)
        if: always()
        run: cargo clippy --all-targets --all-features

      - name: Run tests
        if: always()
        run: cargo test --verbose
